/*
 * wz_about.java
 *
 * Created on __DATE__, __TIME__
 */

package com.FamilyHotelManageSystem.about;

import java.awt.Frame;
import java.awt.Toolkit;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author  __USER__
 */
public class About extends javax.swing.JFrame {

	/** Creates new form wz_about */
	public About(Frame frame) {
		initComponents();
		//设置窗口显示位置的宽和高
		int w = (Toolkit.getDefaultToolkit().getScreenSize().width - 510) / 2;
		int h = (Toolkit.getDefaultToolkit().getScreenSize().height - 290) / 2;
		this.setLocation(w, h);
		this.setTitle("关于我们");
		//新建并且加入左上角标签图标
		ImageIcon icon = new ImageIcon("pic\\2.png");
		this.setIconImage(icon.getImage());
		ImageIcon aIcon = new ImageIcon("pic\\Family0.png");
		//JLabel 对象可以显示文本、图像或同时显示二者。可以通过设置垂直和水平对齐方式，指定标签显示区中标签内容在何处对齐。默认情况下，标签在其显示区内垂直居中对齐。默认情况下，只显示文本的标签是开始边对齐；而只显示图像的标签则水平居中对齐。 还可以指定文本相对于图像的位置。默认情况下，文本位于图像的结尾边上，文本和图像都垂直对齐。
		JLabel aIconLabel = new JLabel(aIcon);
		//设置Jlable的位置
		aIconLabel.setBounds(-50, -10, 345, 70);
		ImageIcon background = new ImageIcon("pic\\背景.PNG");
		// 把背景图片显示在一个标签里面
		JLabel label = new JLabel(background);
		//把标签的大小位置设置为图片刚好填充整个面板,将背景标签添加到窗口里。
		label.setBounds(0, 0, this.getWidth(), this.getHeight());
		JPanel imagePanel = (JPanel) this.getContentPane();
		imagePanel.setOpaque(false);
		// 把背景图片添加到分层窗格的最底层作为背景     
		this.getLayeredPane().add(label, new Integer(Integer.MIN_VALUE));
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setIcon(new javax.swing.ImageIcon(
				"pic\\Family0.png")); // NOI18N

		jLabel2.setForeground(new java.awt.Color(204, 0, 0));
		jLabel2.setText("\u7cfb\u7edf\u540d\u79f0:");

		jLabel3.setForeground(new java.awt.Color(0, 0, 153));
		jLabel3.setText("Family\u9152\u5e97\u7ba1\u7406\u7cfb\u7edf");

		jLabel4.setForeground(new java.awt.Color(204, 0, 0));
		jLabel4.setText("\u540e\u671f\u7ef4\u62a4:");

		jLabel5.setForeground(new java.awt.Color(0, 0, 153));
		jLabel5.setText("信管一班");

		jLabel6.setForeground(new java.awt.Color(153, 0, 0));
		jLabel6.setText("指导老师:");

		jLabel7.setForeground(new java.awt.Color(0, 0, 153));
		jLabel7.setText("博神");

		jLabel8.setForeground(new java.awt.Color(153, 0, 0));
		jLabel8.setText("\u8054\u7cfb\u90ae\u7bb1:");

		jLabel9.setForeground(new java.awt.Color(0, 0, 153));
		jLabel9.setText("ceet@vip.qq.com");

		jLabel10.setForeground(new java.awt.Color(153, 0, 0));
		jLabel10.setText("\u516c\u53f8\u5730\u5740:");

		jLabel11.setForeground(new java.awt.Color(0, 0, 153));
		jLabel11
				.setText("\u6e56\u5317\u5b5d\u611f\u5e02\u7389\u6cc9\u8def17\u53f7");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jLabel1,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addContainerGap(45, Short.MAX_VALUE)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel2)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel3,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				205,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addContainerGap())
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(
																				layout
																						.createSequentialGroup()
																						.addComponent(
																								jLabel6)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(
																								jLabel7,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								226,
																								Short.MAX_VALUE)
																						.addContainerGap())
																		.addGroup(
																				layout
																						.createSequentialGroup()
																						.addComponent(
																								jLabel10)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(
																								jLabel11,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								215,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addContainerGap())
																		.addGroup(
																				layout
																						.createSequentialGroup()
																						.addComponent(
																								jLabel4)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																						.addComponent(
																								jLabel5,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								226,
																								Short.MAX_VALUE)
																						.addContainerGap()))))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addGap(45, 45, 45)
										.addComponent(jLabel8)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jLabel9,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												226, Short.MAX_VALUE)
										.addContainerGap()));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addComponent(
												jLabel1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												59,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(32, 32, 32)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel2)
														.addComponent(jLabel3))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel4)
														.addComponent(jLabel5))
										.addGap(17, 17, 17)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel6)
														.addComponent(jLabel7))
										.addGap(18, 18, 18)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel8)
														.addComponent(jLabel9))
										.addGap(18, 18, 18)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel10)
														.addComponent(jLabel11))
										.addContainerGap(57, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */


	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	// End of variables declaration//GEN-END:variables

}